# Generated by Django 3.2 on 2022-10-12 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('building_age', models.CharField(blank=True, choices=[('1', '0-5'), ('2', '0-10'), ('3', '0-15'), ('4', '0-20'), ('20+', '20+')], default=1, max_length=20, null=True)),
                ('parking', models.IntegerField(blank=True, default=0, null=True)),
                ('rooms', models.IntegerField(blank=True, default=1, null=True)),
                ('bedroom', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('bathroom', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('area', models.FloatField(blank=True, default=0.0, null=True)),
                ('type', models.CharField(blank=True, choices=[('none', 'None'), ('rent', 'Rent'), ('lease', 'Lease'), ('sale', 'Sale')], default='none', max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('none', 'None'), ('apartment', 'Apartment'), ('villas', 'Villas'), ('commercial', 'Commercial'), ('office', 'Office'), ('flat', 'Flat'), ('house', 'House'), ('land', 'House')], default='none', max_length=100, null=True)),
                ('furnished', models.CharField(blank=True, choices=[('semi', 'Semi'), ('Fully', 'Fully'), ('not', 'Not')], default='not', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('deleted', 'Deleted'), ('active', 'Active'), ('suspented', 'Suspented'), ('draft', 'Draft')], default='active', max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('floor_plan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/images/')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_img', to='properties.properties')),
            ],
            options={
                'verbose_name_plural': 'Property Images',
            },
        ),
    ]
