# Generated by Django 3.2 on 2022-10-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofiledetails_options'),
        ('properties', '0003_properties_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdetails'),
        ),
    ]
