# Generated by Django 3.2 on 2022-10-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_properties_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='furnished',
            field=models.CharField(blank=True, choices=[('semi', 'Semi'), ('fully', 'Fully'), ('not', 'Not')], default='not', max_length=100, null=True),
        ),
    ]
