# Generated by Django 3.2 on 2022-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_properties_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(blank=True, choices=[('deleted', 'Deleted'), ('active', 'Active'), ('suspented', 'Suspented'), ('draft', 'Draft'), ('sold', 'Sold'), ('pending', 'Pending'), ('cancel', 'Cancel')], default='active', max_length=100, null=True),
        ),
    ]
