# Generated by Django 3.2 on 2022-10-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_properties_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
