# Generated by Django 3.2 on 2022-10-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_created_at_properties_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
