# Generated by Django 3.2 on 2022-10-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileAdditional',
            new_name='UserProfileDetails',
        ),
    ]
