# Generated by Django 3.2 on 2022-10-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_userprofileadditional_userprofiledetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofiledetails',
            options={'verbose_name_plural': 'User Profile Details'},
        ),
    ]
