# Generated by Django 3.2 on 2022-10-14 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofiledetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiledetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_img', to='user.userdetails'),
        ),
    ]
