# Generated by Django 3.2 on 2022-10-17 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_guestusers_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
